from dais.admins.license_admin import LicenseAdmin
from dais.admins.user_admin import UserAdmin, BaseUserAdmin
from dais.admins.client_admin import ClientAdmin
from dais.admins.clientmodule_admin import ClientModuleAdmin
from dais.admins.form_admin import FormAdmin
from dais.admins.avatar_admin import AvatarAdmin
from dais.admins.voice_admin import VoiceAdmin
from dais.admins.language_admin import LanguageAdmin
from dais.admins.module_admin import ModuleAdmin
from dais.admins.screentype_admin import ScreenTypeAdmin
from dais.admins.group_admin import GroupAdmin
from dais.admins.totem_admin import TotemAdmin
from dais.admins.screen_admin import ScreenAdmin
from dais.admins.logs_admin import LogAdmin
from dais.admins.periodds_admin import PeriodDSAdmin
from dais.admins.periodia_admin import PeriodIAAdmin
from dais.admins.timeslot_admin import TimeSlotAdmin
from dais.admins.contribution_admin import ContributionAdmin
from dais.admins.detail_admin import DetailAdmin
from dais.admins.layer_admin import LayerAdmin
from dais.admins.contributionia_admin import ContributionIAAdmin
from dais.admins.formation_admin import FormationAdmin