# Generated by Django 5.0.4 on 2024-04-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
