# Generated by Django 5.0.4 on 2024-06-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='period',
            new_name='campaignds',
        ),
    ]
