# Generated by Django 5.0.4 on 2024-04-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0002_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=255, verbose_name='indirizzo')),
                ('phone', models.CharField(max_length=20, verbose_name='telefono')),
                ('active', models.BooleanField(default=True, verbose_name='attivo')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.license', verbose_name='licenza')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
    ]
