# Generated by Django 5.0.4 on 2024-06-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0002_rename_period_timeslot_campaignds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='period',
            new_name='campaignai',
        ),
    ]
