# Generated by Django 5.0.4 on 2024-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0003_rename_period_layer_campaignai'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='needs_update',
            field=models.BooleanField(default=False),
        ),
    ]
