# Generated by Django 5.0.4 on 2024-04-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('file', models.FileField(upload_to='avatars/', verbose_name='File')),
                ('voice', models.CharField(max_length=255, verbose_name='Voce')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Data ultimo aggiornamento')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.license', verbose_name='ID Licenza')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatar',
            },
        ),
    ]
