# Generated by Django 5.0.4 on 2024-04-10 12:22

import dais.models.avatar_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0004_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='file',
            field=models.FileField(upload_to=dais.models.avatar_models.avatar_directory_path, verbose_name='File'),
        ),
    ]
