# Generated by Django 5.0.4 on 2024-06-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='license_code',
        ),
    ]
