# Generated by Django 5.0.4 on 2024-04-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0005_alter_avatar_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='license',
        ),
    ]
