# Generated by Django 5.0.4 on 2024-04-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0006_remove_avatar_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='avatars',
            field=models.ManyToManyField(blank=True, to='dais.avatar', verbose_name='Avatares'),
        ),
    ]
