# Generated by Django 5.0.4 on 2024-06-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0007_grouptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='grouptypes',
            field=models.ManyToManyField(blank=True, to='dais.grouptype'),
        ),
    ]
