# Generated by Django 5.0.4 on 2024-04-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0007_license_avatars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='voice',
        ),
    ]
