# Generated by Django 5.0.4 on 2024-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0010_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='voices',
            field=models.ManyToManyField(blank=True, to='dais.voice', verbose_name='Voci'),
        ),
    ]
