# Generated by Django 5.0.4 on 2024-04-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0013_remove_group_total_totems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(verbose_name='Data di installazione')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('screens', models.IntegerField(verbose_name='Schermi')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commenti')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.client', verbose_name='Cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.group', verbose_name='Gruppo')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.license', verbose_name='Licenza')),
            ],
            options={
                'verbose_name': 'Totem',
                'verbose_name_plural': 'Totems',
            },
        ),
    ]
