# Generated by Django 5.0.4 on 2024-04-12 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0014_totem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='license',
        ),
        migrations.AddField(
            model_name='group',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.client', verbose_name='Cliente'),
        ),
    ]
