# Generated by Django 5.0.4 on 2024-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0015_remove_group_license_group_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='client',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='license',
        ),
        migrations.AddField(
            model_name='totem',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='nome'),
        ),
    ]
