# Generated by Django 5.0.4 on 2024-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0016_remove_totem_client_remove_totem_license_totem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Lingua',
                'verbose_name_plural': 'Lingue',
            },
        ),
    ]
