# Generated by Django 5.0.4 on 2024-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0017_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='languages',
            field=models.ManyToManyField(blank=True, to='dais.language', verbose_name='Lingue'),
        ),
    ]
