# Generated by Django 5.0.4 on 2024-04-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0020_periodds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodds',
            options={'verbose_name': 'PeriodoDS', 'verbose_name_plural': 'PeriodiDS'},
        ),
    ]
