# Generated by Django 5.0.4 on 2024-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0021_alter_periodds_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodds',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Attivo'),
        ),
    ]
