# Generated by Django 5.0.4 on 2024-04-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0023_periodia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Ora di inizio')),
                ('end_time', models.TimeField(verbose_name='Ora di fine')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.periodds', verbose_name='ID Periodo')),
            ],
            options={
                'verbose_name': 'Fascia Oraria',
                'verbose_name_plural': 'Fasce Orarie',
            },
        ),
    ]
