# Generated by Django 5.0.4 on 2024-04-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0024_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.timeslot', verbose_name='ID Orario')),
            ],
            options={
                'verbose_name': 'Contributo',
                'verbose_name_plural': 'Contributi',
            },
        ),
    ]
