# Generated by Django 5.0.4 on 2024-04-16 15:20

import dais.models.detail_models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0025_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dais.models.detail_models.detail_directory_path)),
                ('order', models.CharField(choices=[('R', 'Random'), ('N', 'Number')], max_length=1, verbose_name='tipo di ordine')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='data di creazione')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.contribution')),
            ],
            options={
                'verbose_name': 'Dettaglio',
                'verbose_name_plural': 'Dettagli',
            },
        ),
    ]
