# Generated by Django 5.0.4 on 2024-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0026_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome'),
        ),
    ]
