# Generated by Django 5.0.4 on 2024-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0027_detail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='order',
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_random',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ordine casuale'),
        ),
    ]
