# Generated by Django 5.0.4 on 2024-04-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0028_remove_detail_order_contribution_is_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_number', models.IntegerField(verbose_name='Numero del layer')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name="Data dell'ultima aggiornamento")),
                ('trigger', models.CharField(max_length=255, verbose_name='Trigger')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.avatar', verbose_name='Id avatar')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dais.layer', verbose_name='Parente')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.periodia', verbose_name='Id periodoia')),
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
            },
        ),
    ]
