# Generated by Django 5.0.4 on 2024-04-19 13:37

import dais.models.screen_models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0029_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='screens',
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typology', models.CharField(choices=[('HOLOFAN', 'Hologram Fan'), ('LEDWALL', 'LED Wall'), ('SCREEN', 'Screen'), ('TOUCH_SCREEN', 'Touch Screen'), ('PROJECTION', 'Projection')], max_length=50, verbose_name='Tipologia')),
                ('logo', models.FileField(blank=True, null=True, upload_to=dais.models.screen_models.screen_file_path, verbose_name='Logo')),
                ('background', models.FileField(blank=True, null=True, upload_to=dais.models.screen_models.screen_file_path, verbose_name='Sfondo')),
                ('footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data di creazione')),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='dais.totem', verbose_name='Id totem')),
            ],
            options={
                'verbose_name': 'Schermo',
                'verbose_name_plural': 'Schermi',
            },
        ),
    ]
