# Generated by Django 5.0.4 on 2024-04-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0030_remove_totem_screens_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='totem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.totem', verbose_name='Id totem'),
        ),
    ]
