# Generated by Django 5.0.4 on 2024-04-22 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0032_contributionia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data di creazione'),
        ),
    ]
