# Generated by Django 5.0.4 on 2024-04-23 10:45

import dais.models.formation_models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0033_alter_contributionia_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('file', models.FileField(blank=True, null=True, upload_to=dais.models.formation_models.formation_directory_path, verbose_name='File')),
                ('trigger', models.CharField(max_length=255, verbose_name='Trigger')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name="Data Dell'ultimo aggiornamento")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data di creazione')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.language', verbose_name='Lingua ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.layer', verbose_name='Layer ID')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.voice', verbose_name='Voce ID')),
            ],
            options={
                'verbose_name': 'Formazione',
                'verbose_name_plural': 'Formazioni',
            },
        ),
    ]
