# Generated by Django 5.0.4 on 2024-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0034_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Moduli',
            },
        ),
    ]
