# Generated by Django 5.0.4 on 2024-04-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0035_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='modules',
            field=models.ManyToManyField(blank=True, to='dais.module', verbose_name='Moduli'),
        ),
    ]
