# Generated by Django 5.0.4 on 2024-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0037_screentype'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='screentypes',
            field=models.ManyToManyField(blank=True, to='dais.screentype', verbose_name='Tipologie Schermi'),
        ),
    ]
