# Generated by Django 5.0.4 on 2024-04-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0038_license_screentypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='typology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.screentype', verbose_name='Tipologia'),
        ),
    ]
