# Generated by Django 5.0.4 on 2024-04-30 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0039_alter_screen_typology'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Data dell'ultimo aggiornamento"),
        ),
    ]
