# Generated by Django 5.0.4 on 2024-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0040_group_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Attivo'),
        ),
    ]
