# Generated by Django 5.0.4 on 2024-05-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0042_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='client',
        ),
        migrations.CreateModel(
            name='ClientModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Modulo Cliente',
                'verbose_name_plural': 'Moduli Clienti',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='client_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.clientmodule', verbose_name='Clienti'),
        ),
    ]
