# Generated by Django 5.0.4 on 2024-05-06 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0043_remove_form_client_clientmodule_form_client_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.module', verbose_name='Modulo'),
        ),
    ]
