# Generated by Django 5.0.4 on 2024-05-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0044_clientmodule_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='module',
        ),
    ]
