# Generated by Django 5.0.4 on 2024-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0045_remove_form_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
