# Generated by Django 5.0.4 on 2024-05-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0046_module_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('field_type', models.CharField(choices=[('Text', 'Testo'), ('Number', 'Numero'), ('Date', 'Data')], default='text', max_length=50, verbose_name='Tipo di Campo')),
                ('required', models.BooleanField(default=False, verbose_name='Obbligatorio')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.form', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Campo di Form',
                'verbose_name_plural': 'Campi di Form',
                'ordering': ['numero'],
            },
        ),
    ]
