# Generated by Django 5.0.4 on 2024-05-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0048_alter_formfield_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Dato')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.form', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Dato del form',
                'verbose_name_plural': 'Dati del form',
            },
        ),
    ]
