# Generated by Django 5.0.4 on 2024-05-08 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0049_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Data dell'ultimo aggiornamento"),
        ),
    ]
