# Generated by Django 5.0.4 on 2024-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0051_clientmodule_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='forms',
            field=models.ManyToManyField(blank=True, to='dais.form', verbose_name='Form'),
        ),
    ]
