# Generated by Django 5.0.4 on 2024-05-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0052_group_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dais.form', verbose_name='Form'),
        ),
    ]
