# Generated by Django 5.0.4 on 2024-05-14 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0053_alter_formfield_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchScreenInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Data dell'ultimo aggiornamento")),
                ('client_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.clientmodule', verbose_name='Moduli Clienti')),
            ],
            options={
                'verbose_name': 'Modulo CLiente',
                'verbose_name_plural': 'Moduli CLienti',
            },
        ),
    ]
