# Generated by Django 5.0.4 on 2024-05-15 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0054_touchscreeninteractions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touchscreeninteractions',
            options={},
        ),
        migrations.AlterField(
            model_name='touchscreeninteractions',
            name='client_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.clientmodule'),
        ),
        migrations.AlterField(
            model_name='touchscreeninteractions',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='touchscreeninteractions',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
