# Generated by Django 5.0.4 on 2024-05-15 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0055_alter_touchscreeninteractions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterField(
            model_name='group',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.client'),
        ),
        migrations.AlterField(
            model_name='group',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='forms',
            field=models.ManyToManyField(blank=True, to='dais.form'),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='typology',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Digital Signage', 'Digital Signage')], max_length=24),
        ),
    ]
