# Generated by Django 5.0.4 on 2024-05-17 15:36

import dais.models.button_models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0056_alter_group_options_alter_group_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipologia Pulsante',
                'verbose_name_plural': 'Tipologie Pulsanti',
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=dais.models.button_models.button_directory_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.form')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.touchscreeninteractions')),
                ('button_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.buttontype')),
            ],
        ),
    ]
