# Generated by Django 5.0.4 on 2024-05-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0057_buttontype_button'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={},
        ),
        migrations.AddField(
            model_name='license',
            name='buttontypes',
            field=models.ManyToManyField(blank=True, to='dais.buttontype'),
        ),
        migrations.AlterField(
            model_name='license',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='avatars',
            field=models.ManyToManyField(blank=True, to='dais.avatar'),
        ),
        migrations.AlterField(
            model_name='license',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='license',
            name='languages',
            field=models.ManyToManyField(blank=True, to='dais.language'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='modules',
            field=models.ManyToManyField(blank=True, to='dais.module'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='screentypes',
            field=models.ManyToManyField(blank=True, to='dais.screentype'),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='license',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='voices',
            field=models.ManyToManyField(blank=True, to='dais.voice'),
        ),
    ]
