# Generated by Django 5.0.4 on 2024-05-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0058_alter_license_options_license_buttontypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='total_totem',
            field=models.IntegerField(default=0),
        ),
    ]
