# Generated by Django 5.0.4 on 2024-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0060_alter_totem_options_alter_totem_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='installation_date',
            field=models.DateField(null=True),
        ),
    ]
