# Generated by Django 5.0.4 on 2024-05-31 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0061_alter_totem_installation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmodule',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientmodule',
            name='name',
        ),
        migrations.AlterField(
            model_name='clientmodule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.client'),
        ),
        migrations.AlterField(
            model_name='clientmodule',
            name='groups',
            field=models.ManyToManyField(blank=True, to='dais.group'),
        ),
        migrations.AlterField(
            model_name='clientmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dais.module'),
        ),
    ]
