# Generated by Django 5.0.4 on 2024-06-03 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0062_alter_clientmodule_options_remove_clientmodule_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
        migrations.RemoveField(
            model_name='log',
            name='totem',
        ),
        migrations.AddField(
            model_name='log',
            name='license',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dais.license'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='typology',
            field=models.CharField(choices=[('Artificial Intelligence', 'AI'), ('Digital Signage', 'DS')], max_length=24),
        ),
    ]
