# Generated by Django 5.0.4 on 2024-06-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dais', '0063_alter_log_options_remove_log_totem_log_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='totem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dais.totem'),
        ),
        migrations.AlterField(
            model_name='log',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dais.license'),
        ),
    ]
